tasks:
  build:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  lint:
    image: node:carbon
    command:
      - yarn
    args:
      - lint
  test:
    image: node:carbon
    command:
      - yarn
    args:
      - test
  deploy:
    image: node:carbon
    when: \/heads\/master$
    command:
      - bash
    args:
      - ./scripts/deploy.sh
    env:
      - AWS_KEY
      - AWS_SECRET
